# Generated by Django 5.0.7 on 2024-07-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='house_images/')),
                ('add', models.CharField(max_length=200)),
                ('add1', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('price', models.FloatField()),
                ('about', models.CharField(max_length=200)),
                ('condition', models.CharField(max_length=50)),
            ],
        ),
    ]
