# Generated by Django 5.0.7 on 2024-07-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homedetails',
            name='status',
            field=models.CharField(default='not rented', max_length=50),
        ),
    ]
