# Generated by Django 5.0.7 on 2024-07-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0002_homedetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homedetails',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
