# Generated by Django 5.0.7 on 2024-08-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0006_rentdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentdetails',
            name='total_price',
            field=models.IntegerField(default=1),
        ),
    ]
