# Generated by Django 5.0.7 on 2024-08-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0007_alter_rentdetails_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homedetails',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
