# Generated by Django 5.0.7 on 2024-08-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0008_alter_homedetails_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homedetails',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rentdetails',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
